# Generated by Django 4.2.16 on 2025-08-08 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('BMI', models.FloatField()),
                ('hypertensive', models.FloatField()),
                ('diabetes', models.FloatField()),
                ('depression', models.FloatField()),
                ('heart_rate', models.FloatField()),
                ('systolic_bp', models.FloatField()),
                ('diastolic_bp', models.FloatField()),
                ('respiratory_rate', models.FloatField()),
                ('temperature', models.FloatField()),
                ('sp_o2', models.FloatField()),
                ('urine_output', models.FloatField()),
                ('rbc', models.FloatField()),
                ('mch', models.FloatField()),
                ('mchc', models.FloatField()),
                ('mcv', models.FloatField()),
                ('rdw', models.FloatField()),
                ('creatinine', models.FloatField()),
                ('urea_nitrogen', models.FloatField()),
                ('glucose', models.FloatField()),
                ('blood_potassium', models.FloatField()),
                ('blood_sodium', models.FloatField()),
                ('blood_calcium', models.FloatField()),
                ('chloride', models.FloatField()),
                ('magnesium_ion', models.FloatField()),
                ('PH', models.FloatField()),
                ('lactic_acid', models.FloatField()),
                ('PCO2', models.FloatField()),
                ('prediction_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
